/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_leo_helloworld_Helloworld */

#ifndef _Included_com_leo_helloworld_Helloworld
#define _Included_com_leo_helloworld_Helloworld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_leo_helloworld_Helloworld
 * Method:    getPrint
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_leo_helloworld_Helloworld_getPrint
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
